CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50)
)
CREATE TABLE  Customers
(
CustomerID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50),
Birthday DATE,
CityID INT REFERENCES Cities(CityID)
)
CREATE TABLE Orders
(
OrderID INT PRIMARY KEY IDENTITY,
CustomerID INT REFERENCES Customers(CustomerID)
)
CREATE TABLE ItemTypes
(
ItemTypeID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50)
)
CREATE TABLE Items
(
ItemID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50),
ItemTypeID INT REFERENCES ItemTypes(ItemTypeID)
)
CREATE TABLE OrderItems
(
OrderID INT,
ItemID INT,
PRIMARY KEY(OrderID,ItemID),
FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY(ItemID) REFERENCES Items(ItemID)
)