CREATE TABLE Subjects
(
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName VARCHAR(50)
)
CREATE TABLE Majors
(
MajorID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50)
)
CREATE TABLE Students
(
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber INT,
StudentName VARCHAR(50),
MajorID INT REFERENCES Majors(MajorID)
)
CREATE TABLE Payments
(
PaymentID INT PRIMARY KEY IDENTITY,
PaymentDate DATE,
PaymentAmount DECIMAL(18,2),
StudentID INT REFERENCES Students(StudentID)
)
CREATE TABLE Agenda
(
StudentID INT NOT NULL,
SubjectID INT NOT NULL,
PRIMARY KEY (StudentID, SubjectID),
FOREIGN KEY(StudentID) REFERENCES Students(StudentID),
FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
)